import { Metadata } from "next";

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: {
      template: "Privacy Policy",
      default: "Privacy Policy",
    },
    description: "Tripotter privacy policies",
  };
}

export default function PrivacyPolicy() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-12 text-gray-800 dark:bg-gray-950 dark:text-gray-200">
      <h1 className="text-4xl font-bold mb-2 text-gray-900 dark:text-gray-100">Tripotter Privacy Policy</h1>
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-8">
        Effective Date: July 20, 2025 • Last Updated: July 20, 2025
      </p>

      <p className="mb-6">
        Tripotter ("we", "our", or "us") respects your privacy and is committed
        to protecting your data. This Privacy Policy explains how we collect,
        use, share, and safeguard your information when you use our platform,
        including our website, mobile app, and related services ("Service"). By
        using Tripotter, you agree to this policy.
      </p>

      <Section title="1. Information We Collect">
        <Subsection
          title="1.1 Information You Provide"
          items={[
            "Account data (email, password, name, phone)",
            "Profile data (travel interests, photos, preferences)",
            "User-generated content (posts, reviews, edits, comments)",
            "Booking or e-commerce data (e.g., shipping address, billing info)",
          ]}
        />
        <Subsection
          title="1.2 Automatically Collected Data"
          items={[
            "Device identifiers, IP address, browser, and OS data",
            "Usage data (pages visited, features clicked)",
            "Geolocation data for maps, suggestions, and booking",
            "Cookies, pixels, and analytics trackers",
          ]}
        />
        <Subsection
          title="1.3 AI and Interaction History"
          items={[
            "Trip suggestions generated by AI",
            "Interaction logs for content generation or editing tools",
            "Messaging and gamification data (points, rewards, leaderboards)",
          ]}
        />
      </Section>

      <Section
        title="2. How We Use Your Information"
        items={[
          "Deliver, improve, and personalize services",
          "Show AI-generated itineraries and suggestions",
          "Enable features like chat, groups, gamification, and reviews",
          "Manage bookings, transactions, and payments",
          "Moderate content and enforce platform standards",
          "Communicate service updates or promotional content",
          "Ensure security and legal compliance",
        ]}
      />

      <Section title="3. Payments and Financial Data">
        <h4 className="font-semibold mt-4 mb-2 text-gray-900 dark:text-gray-100">3.1 Supported Methods</h4>
        <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300">
          <li>Google Pay</li>
          <li>Pathao Pay</li>
          <li>Visa, Mastercard, Debit Cards</li>
          <li>Future: Cryptocurrency support (e.g., USDT, BTC, ETH)</li>
        </ul>
        <p className="mt-2">
          Payments are securely handled via PCI-DSS-compliant providers. We do
          not store card numbers.
        </p>
      </Section>

      <Section
        title="4. Storage & Infrastructure"
        items={[
          "AWS (Amazon Web Services) and Google Cloud infrastructure",
          "Integrated services and APIs from: Google Maps, OpenAI, Stripe, PayPal, Booking platforms",
          "Third-party hotel, flight, or tour booking APIs",
          "We follow industry best practices to prevent unauthorized access.",
        ]}
      />

      <Section
        title="5. Sharing Your Data"
        items={[
          "We do not sell your personal data.",
          "We may share information with third-party processors (e.g., Google, Stripe, map services)",
          "For legal obligations or enforcement",
          "During business transfers or acquisitions",
        ]}
      />

      <Section
        title="6. Community, Social, and Content Sharing"
        items={[
          "Content like posts, reviews, and comments may be public",
          "Your profile name, username, and picture may be visible to others",
          "Gamification scores or rankings may appear in leaderboards",
          "Community moderation is done via AI and human moderators",
        ]}
      />

      <Section title="7. AI & Moderation">
        <p>We use AI for:</p>
        <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300">
          <li>Travel plan generation and content suggestions</li>
          <li>Real-time content moderation and flagging</li>
          <li>Editing photos, posts, or user input</li>
        </ul>
        <h4 className="font-semibold mt-4 mb-2 text-gray-900 dark:text-gray-100">7.1 AI Data Practices</h4>
        <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300">
          <li>AI-generated content is not guaranteed to be 100% accurate</li>
          <li>
            You may not use platform content for external AI training without
            our permission
          </li>
          <li>
            AI content is logged and stored securely for platform improvement
            only
          </li>
        </ul>
      </Section>

      <Section
        title="8. Your Rights and Choices"
        items={[
          "Access, update, or delete your personal data",
          "Opt out of marketing and analytics",
          "Control location permissions in your device settings",
          "Request account or content deletion by contacting us at: shadmanislam27@gmail.com",
        ]}
      />

      <Section
        title="9. Data Retention & Security"
        items={[
          "We retain data as long as necessary to deliver services or comply with legal obligations.",
          "End-to-end encryption",
          "Role-based access control",
          "Tokenized payment data storage",
          "Moderation logs and audit trails",
        ]}
      />

      <Section title="10. Children’s Privacy">
        <p>
          Tripotter is not intended for users under 18. We do not knowingly
          collect data from minors.
        </p>
      </Section>

      <Section
        title="11. Future Features & Consent"
        items={[
          "Gamification (leaderboards, badges, XP, rewards)",
          "In-app cryptocurrency payments",
          "Tripotter Coins or Loyalty Points",
          "AI-based matchmaking for group travel",
          "By continuing to use the platform, you consent to future updates, subject to this policy.",
        ]}
      />

      <Section title="12. Updates to This Policy">
        <p>
          We may update this Privacy Policy when we introduce new features,
          change services, or comply with updated laws. Major updates will be
          announced via:
        </p>
        <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300">
          <li>In-app notifications</li>
          <li>Email alerts</li>
          <li>Banner messages on the website</li>
        </ul>
        <p className="mt-2">
          Continued use of the platform indicates your acceptance of the updated
          policy.
        </p>
      </Section>

      <Section title="13. Contact Information">
        <p>
          Email:{" "}
          <a
            href="mailto:shadmanislam27@gmail.com"
            className="text-blue-600 underline dark:text-blue-400"
          >
            shadmanislam27@gmail.com
          </a>
        </p>
        <p>Phone: +8801627439774</p>
      </Section>

      <p className="text-sm mt-10 text-gray-500 dark:text-gray-400">
        Legal Note: This Privacy Policy complies with GDPR (EU), CCPA
        (California), PDPA (Bangladesh), global privacy frameworks, and industry
        standards used by major social and travel platforms.
      </p>
    </main>
  );
}

function Section({
  title,
  children,
  items,
}: {
  title: string;
  children?: React.ReactNode;
  items?: string[];
}) {
  return (
    <section className="mb-8">
      <h2 className="text-2xl font-semibold mb-3 text-gray-900 dark:text-gray-100">{title}</h2>
      {items && (
        <ul className="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300">
          {items.map((item, idx) => (
            <li key={idx}>{item}</li>
          ))}
        </ul>
      )}
      {children}
    </section>
  );
}

function Subsection({ title, items }: { title: string; items: string[] }) {
  return (
    <div className="mb-4">
      <h4 className="font-medium text-gray-900 dark:text-gray-100">{title}</h4>
      <ul className="list-disc list-inside pl-4 space-y-1 text-gray-700 dark:text-gray-300">
        {items.map((item, idx) => (
          <li key={idx}>{item}</li>
        ))}
      </ul>
    </div>
  );
}
